/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan8;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane; 
/**
 *
 * @author User
 */
public class FormServer extends javax.swing.JFrame {
    static ServerSocket $$;
    static Socket $;
    static DataInputStream din;
    static DataOutputStream dout;
    static String namaClient;
    /**
     * Creates new form FormServer
     */
    public FormServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi_pesanserver = new javax.swing.JTextArea();
        txt_pesanserver = new javax.swing.JTextField();
        btn_kirimserver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sisi Server");

        isi_pesanserver.setColumns(20);
        isi_pesanserver.setRows(5);
        jScrollPane1.setViewportView(isi_pesanserver);

        btn_kirimserver.setText("KIRIM");
        btn_kirimserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimserverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_pesanserver)
                        .addGap(18, 18, 18)
                        .addComponent(btn_kirimserver, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pesanserver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kirimserver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kirimserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimserverActionPerformed
        // TODO add your handling code here:
         try {
            String msgout = txt_pesanserver.getText().trim();
            if (msgout.isEmpty() || dout == null) return;

            dout.writeUTF(msgout);  // Kirim ke client
            isi_pesanserver.append("\nMe: " + msgout);  // Tampilkan juga di sisi server
            isi_pesanserver.setCaretPosition(isi_pesanserver.getDocument().getLength());
            txt_pesanserver.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengirim pesan!\n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_kirimserverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormServer().setVisible(true);
            }
        });
        
        try{
            $$ = new ServerSocket(5678); // ubah sesuai 4 npm di belakang
            // misal npm 12345678 jadi yang ditulis 5678
            $ = $$.accept();
            
            din = new DataInputStream($.getInputStream());
            dout = new DataOutputStream($.getOutputStream());
            
            String firstMsg = din.readUTF();
            if(firstMsg.startsWith("[NAMA]")){
                namaClient = firstMsg.replace("[NAMA]", "").trim();
                if(namaClient.isEmpty()){
                    namaClient = "client";
                }
                isi_pesanserver.append("Terhubung dengan : "+ namaClient + "\n");
            }
            
            String pesanmasuk = "";
            while(!pesanmasuk.equals("keluar")){
                pesanmasuk = din.readUTF();
                isi_pesanserver.append("\n" + namaClient + ": " + pesanmasuk);
                isi_pesanserver.setCaretPosition(isi_pesanserver.getDocument().getLength());
            }
        }catch(Exception e){
            isi_pesanserver.append("\n[ERROR] " + e.getMessage());
            isi_pesanserver.setCaretPosition(isi_pesanserver.getDocument().getLength());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kirimserver;
    private static javax.swing.JTextArea isi_pesanserver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_pesanserver;
    // End of variables declaration//GEN-END:variables
}
