/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan8;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class FormClient extends javax.swing.JFrame {
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    /**
     * Creates new form FormClient
     */
    public FormClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi_pesanclient = new javax.swing.JTextArea();
        txt_pesanclient = new javax.swing.JTextField();
        btn_kirimclient = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Sisi Client");

        isi_pesanclient.setColumns(20);
        isi_pesanclient.setRows(5);
        jScrollPane1.setViewportView(isi_pesanclient);

        btn_kirimclient.setText("KIRIM");
        btn_kirimclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kirimclientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txt_pesanclient)
                                .addGap(18, 18, 18)))
                        .addComponent(btn_kirimclient, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_kirimclient, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(txt_pesanclient))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kirimclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kirimclientActionPerformed
        // TODO add your handling code here:
        try {
            String msgout = txt_pesanclient.getText().trim();
            if (msgout.isEmpty() || dout == null) return;

            dout.writeUTF(msgout);  // Kirim ke server
            isi_pesanclient.append("\nMe: " + msgout);  // Tampilkan juga di sisi client
            isi_pesanclient.setCaretPosition(isi_pesanclient.getDocument().getLength());
            txt_pesanclient.setText(""); // Kosongkan field

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mengirim pesan!\n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_kirimclientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormClient().setVisible(true);
            }
        });
        
        try {
            // Minta input dari user
            String ip = JOptionPane.showInputDialog("Masukkan IP Server:", ""); // Ip bisa menggunakan 127.0.0.1 atau 0.0.0.0
            String portStr = JOptionPane.showInputDialog("Masukkan Port Server:", ""); // Nanti masukkan sesuai port di sisiServer atau npm
            String nama = JOptionPane.showInputDialog("Masukkan Nama Anda:");
            if (nama == null || nama.trim().isEmpty()) {
                nama = "User";  // Default nama
            }
            int port = Integer.parseInt(portStr);

            // Koneksi ke server
            s = new Socket(ip, port);
            din = new DataInputStream(s.getInputStream());
            dout = new DataOutputStream(s.getOutputStream());

            // Kirim nama ke server duluan
            dout.writeUTF("[NAMA]" + nama);  // Penanda nama

            // Terima pesan dari server
            String pesanmasuk = "";
            while (!pesanmasuk.equals("keluar")) {
                pesanmasuk = din.readUTF();
                isi_pesanclient.append("\nAdmin : " + pesanmasuk);
                isi_pesanclient.setCaretPosition(isi_pesanclient.getDocument().getLength());
            }

        } catch (Exception e) {
            isi_pesanclient.append("\n[ERROR] " + e.getMessage());
            isi_pesanclient.setCaretPosition(isi_pesanclient.getDocument().getLength());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_kirimclient;
    private static javax.swing.JTextArea isi_pesanclient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_pesanclient;
    // End of variables declaration//GEN-END:variables
}
